service: dioAWSIaC

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: us-east-1
  iam:
      role:
          statements:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodv:GetItem
                - dynamodb:Scan
              Resource:
                - arn:aws:dynamodb:us-east-1:817995152317:table/ItemTableNew


functions:
  hello:
    handler: src/hello.handler
    events:
      - http:
          path: /
          method: get
  insertItem:
    handler: scr/insertItem.handler
    events:
      - http:
          path: /item
          method: post
  fetchItems:
    handler: scr/fetchItems.handler
    events:
      - http:
          path: /items
          method: get
  fetchItem:
    handler: scr/fetchItem.handler
    events:
      - http:
          path: /items/{id}
          method: get
  updateItem:
    handler: scr/updateItem.handler
    events:
      - http:
          path: /items/{id}
          method: put



resources:
  Resources:
    ItemTable:
      Type: AWS::DynamoDB::Table
      Properties:
          TableName: ItemTableNew
          BillingMode: PAY_PER_REQUEST
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH